#screen dimensions
SCREEN_WIDTH : 800

#framerate
FPS : 60

#define game variables
GRAVITY : 0.75
SCROLL_THRESH : 200
TIMER: 360
ROWS : 16
COLS : 150
TILE_TYPES : 21
MAX_LEVELS : 3
screen_scroll : 0
bg_scroll : 0
level : 1
start_game : False
start_intro : False
ENEMY_SCORE: 200
LEVEL_SCORE: 50

#define player action variables
moving_left : False
moving_right : False
shoot : False
grenade : False
grenade_thrown : False
